language: objective-c
osx_image: xcode10.1
env:
  matrix:
    - TEST_DESTINATION="platform=iOS Simulator,OS=12.1,name=iPad Pro (9.7-inch)"
    - TEST_DESTINATION="platform=iOS Simulator,OS=12.1,name=iPhone XS"
script:
  - set -o pipefail && xcodebuild -workspace events\ manager.xcworkspace -scheme events\ manager -destination "$TEST_DESTINATION" build test | xcpretty
